openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/energiesprong/user/0.0.1
info:
  version: "0.0.2"
  title: Stroomversnelling UDB Resource Server API
  description: >-
    This API describes how to access user resources for client applications and the performance database. The full documentation for this API (still under development) can be requested by sending an email to mwitkamp@stroomversnelling.nl.
security:
  - JWTBearerAuth: []

paths:
  /contract:
    get:
      summary: Get all contracts - role per connection.
      description: 
        A list of all contracts. Contracts indicate the time bound role of the user against a particular connection. 
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/contractList"
  /connection:
    get:
      summary: Get all connections
      description:
        A list of all connections. Connections are devices/locations with data to which a user has a contract. A PDB token will limit results to connection_ids associated with that PDB.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/connectionList"
  /pdb:
    get:
      summary: Get all PDBs
      description:
        A list of URLs of the PDB resource servers. Only accessible with a user token.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: "#/components/schemas/pdbUrlList"
components:
  schemas:
    contract:
      type: object
      required:
        - connectionId
        - role
        - start
        - end
      properties:
        connectionId:
          $ref: "#/components/schemas/connection/properties/connectionId" 
        start:
          $ref: "#/components/schemas/dateTimeFormatReadOnly" 
        end:
          $ref: "#/components/schemas/dateTimeFormatReadOnly" 
        role:
          type: string
          description: The role can be either "", "", "", "", or "".
          readOnly: true
    connection:
      type: object
      required:
        - connectionId
        - pdbUrl
      properties:
        connectionId:
          type: string
          description: the unique identifier, string, 20 characters, randomly generated by UDB
          readOnly: true
        pdbUrl:
          type: string
          description: the URL of the PDB resource server associated with this connection_id
          readOnly: true
        address:
          type: string
          description: the location / address of the connection
          readOnly: 
    pdbUrlList:
      type: array
      items:
        $ref: "#components/schemas/connection/pdbUrl"
    connectionList:
      type: array
      items:
        $ref: "#/components/schemas/connection"
    contractList:
      type: array
      items:
        $ref: "#/components/schemas/contract"
    dateTimeFormatReadOnly:
      type: string
      description: ISO8601 date time of the user creation date defined by "YYYY-MM-DDTHH:MM:SS±HH:MM" (e.g. YYYY-MM-DDTHH:MM:SS±HH:MM CET time)
      readOnly: true
  securitySchemes:
  
    JWTBearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      
    AuthorizationCode:
      type: oauth2
      flows:
        authorizationCode:
          # The Authorization Code is required for Single Page Apps and Authorization Code with PKCE is required for Native Apps
          authorizationUrl: 'https://{authorization-server}/authorize'
          tokenUrl: 'https://{authorization-server}/token'
          refreshUrl: 'https://{authorization-server}/refresh'
          scopes:
            read: Grants read access to resources
            write: Grants write access for some user profile data
            admin: Grants administrative access to manage users

    AuthorizationCodePKCE:
      type: oauth2
      flows:
        authorizationCode:
          # The Authorization Code is required for Single Page Apps and Authorization Code with PKCE is required for Native Apps
          authorizationUrl: 'https://{authorization-server}/authorizePKCE'
          tokenUrl: 'https://{authorization-server}/token'
          refreshUrl: 'https://{authorization-server}/refresh'
          scopes:
            read: Grants read access to resources
            write: Grants write access for some user profile data
            admin: Grants administrative access to manage users
    
    ResourceOwner:
      type: oauth2
      flows:
        # The Resource Owner Flow is optional for secure environments
        password:
          tokenUrl: 'https://{authorization-server}/token'
          refreshUrl: 'https://{authorization-server}/refresh'
          scopes:
            read: Grants read access to resources
            write: Grants write access for some user profile data
            admin: Grants administrative access to manage users
      
    InternalSecureApp:
      type: oauth2
      flows: 
        # The Client Credentials Flow is optional but not recommended
        clientCredentials:
          tokenUrl: '{authorization-server}/token'
          refreshUrl: 'https://{authorization-server}/refresh'
          scopes:
            read: allows reading resources
            write: allows writing resources